services:

  receiptWriteOff:
    #image: ghcr.io/rpry/otus_webapi:2.2
    image: receiptwriteoff
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:5100"
      "ConnectionString": "Host=postgres;Port=5432;Database=receipt;UserId=postgres;Password=password"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5101:5100"
 
networks:
  default:
    name: myLocalNetwork # создана извне: docker network create --driver=bridge myLocalNetwork
    external: true